# Generated by Django 5.0.4 on 2024-04-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_threatsource_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatsource',
            name='url',
        ),
        migrations.AddField(
            model_name='threatsource',
            name='address',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
